// Generated by CoffeeScript 1.6.2
(function() {
  var isArray, isNumber, isObject, isString, randomArrayMember, randomBoolean, randomProperty, randomRange, _ref;

  _ref = require('underscore'), isObject = _ref.isObject, isNumber = _ref.isNumber, isArray = _ref.isArray, isString = _ref.isString;

  module.exports = function(arg) {
    if (arg == null) {
      return randomBoolean();
    }
    if (isArray(arg) || isString(arg)) {
      return randomArrayMember(arg);
    }
    if (isNumber(arg)) {
      return randomRange(arg);
    }
    if (isObject(arg)) {
      return randomProperty(arg);
    }
    return null;
  };

  randomBoolean = function() {
    return !!randomRange(0);
  };

  randomArrayMember = function(arr) {
    var idx;

    idx = randomRange(arr);
    return arr[idx];
  };

  randomRange = function(rangeOrArray) {
    if (isArray(rangeOrArray)) {
      rangeOrArray = rangeOrArray.length;
    }
    return Math.floor(Math.random() * rangeOrArray);
  };

  randomProperty = function(obj) {
    var idx, keys;

    keys = Object.keys(obj);
    if (!(keys.length > 0)) {
      return null;
    }
    if (keys.length === 1) {
      return obj[keys[0]];
    }
    idx = randomRange(keys);
    return obj[keys[idx]];
  };

}).call(this);
